# SPDX-License-Identifier: MPL-2.0

[project]
name = "chimichanga"
description = "Munition (Chimichanga) Elixir application"

[container]
base = "cgr.dev/chainguard/wolfi-base:latest"

[build]
builder = "elixir"
