# SPDX-License-Identifier: PMPL-1.0-or-later

[project]
name = "chimichanga"
description = "Munition (Chimichanga) Elixir application"

[container]
base = "cgr.dev/chainguard/wolfi-base:latest"

[build]
builder = "elixir"
